<a href="https://colab.research.google.com/github/imanSoratiAshtiani/machin-learning-fav/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/visiont3lab/tecnologie_data_science/blob/master/book/docs/python/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

An array object represents a multidimensional, homogeneous array of fixed-size items

In [ ]:
country = np.array(['USA', 'Japan', 'UK', 'Celestopoli', 'India', 'China'])
print(country)

['USA' 'Japan' 'UK' 'Celestopoli' 'India' 'China']


When you make numpy array using np.array than it would create a copy of the object array and would not reflect changes to the original array (with default parameters). On the other hand if you use np.asarray() than it would reflect changes to the original array.



In [ ]:
x = np.array([2,3,1,0])

In [ ]:
x

array([2, 3, 1, 0])

In [ ]:
x.shape

(4,)

In [ ]:
y = np.asarray([4,5,3,1])

In [ ]:
y

array([4, 5, 3, 1])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
y = np.array([[2,3,1,0],[1,1,1,1]])
y.shape

(2, 4)

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
k =np.ones((2, 3))
k

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
k.shape

(2, 3)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, dtype=float) # default strp=1

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.linspace(1., 4.,num=10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [ ]:
np.linspace(1., 4.,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [ ]:
x = np.array([3, 6, 9, 12])

In [ ]:
x/3.0
x

array([ 3,  6,  9, 12])

In [ ]:
print(x)

[ 3  6  9 12]


In [ ]:
z = np.array([2,3,1,0])

In [ ]:
np.sort(z)

array([0, 1, 2, 3])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[9, 8, 7], [6, 5, 4]])

In [ ]:
c = np.concatenate((a, b))
c

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
c.shape

(4, 3)

In [ ]:
np.ones((2, 2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

In [ ]:
## Conversion to an array:

import numpy as np

# from list
my_list = [1, 2, 3, 4, 5, 6, 7, 8]

my_list = np.asarray(my_list)
#type(my_list)
my_list

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# from tuple
my_tuple = ([8, 4, 6], [1, 2, 3])
type(my_tuple)

tuple

In [ ]:
my_tuple = np.asarray(my_tuple)
my_tuple

array([[8, 4, 6],
       [1, 2, 3]])

In [ ]:
#Array to list
a = np.array([1, 2, 3, 4, 5])

b = a.tolist()
b

[1, 2, 3, 4, 5]

In [ ]:
#save array to drive
a = np.array([1, 2, 3, 4, 5])

np.savetxt("il_mio_array.csv", a)

In [ ]:
# il filse csv deve essere sul drive
from google.colab import files
files.download("il_mio_array.csv")

In [ ]:
#######################################################

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b =np.append(a,[10,11,12,13])
b

array([ 1,  2,  3, 10, 11, 12, 13])

In [ ]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a+b
c

array([2, 4, 6])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[400], [800]])

c = np.append(a, b)
c

array([  1,   2,   3,   4,   5,   6, 400, 800])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[400], [800]])

c = np.append(a, b, axis = 1)
c

array([[  1,   2,   3, 400],
       [  4,   5,   6, 800]])

In [ ]:
d = np.array([1, 2, 3])
e = np.insert(a, 1, 90) ## specify whick index add the value we want
e

array([ 1, 90,  2,  3,  4,  5,  6])

In [ ]:
d = np.array([1, 2, 3])
e = np.insert(d, 0, 60) ## specify whick index add the value we want
e

array([60,  1,  2,  3])

In [ ]:
len(d)

3

In [ ]:
d = np.array([1, 2, 3])

e = np.insert(d, 3, 90) ## specify whick index add the value we want
e

array([ 1,  2,  3, 90])

In [ ]:
#APPEND A ROW

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = np.append(a, [[50, 60, 70]], axis = 0)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [50, 60, 70]])

In [ ]:
## se volessi per colonna?
a = np.array([[1, 2, 3], [4, 5, 6]])

c = np.array([[50],[60]])
b = np.append(a, c, axis = 1)
b

array([[ 1,  2,  3, 50],
       [ 4,  5,  6, 60]])

In [ ]:
### Delete an element
x = np.array([1, 2, 3])

x= np.delete(x, 1, axis = 0)
x

array([1, 3])

In [ ]:
#delete an entire row (axis = 0)
x = np.array([[1, 2, 3], [4, 5, 6], [10, 20, 30]])

x = np.delete(x, 2, axis = 0)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.shape

(2, 3)

In [ ]:
#delete an entire column (axis = 1)
x = np.array([[1, 2, 3], [4, 5, 6], [10, 20, 30]])

x = np.delete(x, 2, axis = 1)
x

array([[ 1,  2],
       [ 4,  5],
       [10, 20]])

In [ ]:
#find the index value

a = np.array([1, 2, 3, 4, 5])

print("il valore 5 si trova all'index: ", np.where(a == 5))

il valore 5 si trova all'index:  (array([4]),)


In [ ]:
######### automatic addition

addizione = lambda x: x + 2

a = np.array([1, 2, 3, 4, 5, 6])

b = addizione(a)
b

array([3, 4, 5, 6, 7, 8])

In [ ]:
moltiplicazione = lambda x: x**2

a = np.array([1, 2, 3, 4, 5, 6])

b = moltiplicazione(a)
b

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
età=18

if età <18:
    print('sei minorenne')
else:
    print('sei maggiorenne')

sei maggiorenne


In [ ]:
età=18

if età <10:
    print('sei un bimbo')
elif età<=18:
    print('sei un regaz')
elif età<50:
    print('sei un boomer')
else:
    print('bella vecchio! sei anziano')

sei un regaz


In [ ]:
età=50
patente=False

if età >=18 and patente==True:
    print('puoi guidare finalmente la tua auto da sogno')
elif età >=18 and patente==False:
    print('no patente, no party')
else:
    print('mi dispiace, ritenta quando sarai più grande!!')

no patente, no party


## Funzioni

In [ ]:
def somma_due_numeri(a,b): ## a,b sono argomenti
    #print('questa funzione somma due numeri:')
    risultato = a + b
    return risultato
# OUTPUT DI UNA FUNZIONE è IL VALORE DEL SUO RETURN
# TUTTE LE FUNZIONI HANNO UN RETURN

In [ ]:
## input

In [ ]:
x =input()
#x = input('inserire qualcosa   ')

In [ ]:
type(x)

In [ ]:
### PROGRAMMA
print('questo è il mio programma in python')

nome=input('inserire il tuo nome  ') 
print('buon pomeriggio  '+nome+'  spero tu stia imparando tantissimo!')

In [ ]:
età = input('quanti anni hai?')
print('Bene!!! dunque hai '+ età + '  anni. Il porssimo anno ne avrai '+ str(int(età)+1))